<?php

/**
 * @file
 * Contains media_video_micromodal.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_video_micromodal_help($route_name, RouteMatchInterface $route_match): string {
  // Initialize the return variable.
  $output = '';
  switch ($route_name) {
    // Main module help for the media_video_micromodal module.
    case 'help.page.media_video_micromodal':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays media in a modal using micromodal.js.') . '</p>';
  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function media_video_micromodal_theme(): array {
  return [
    'media_video_micromodal' => [
      'render element' => 'children',
      'variables' => [
        'modal_id' => NULL,
        'linked_item' => NULL,
        'iframe_src' => NULL,
      ],
    ],
  ];
}
