version: 1.3.0
services:
  - mysql
  - php:
      version: 7.4
  - composer:
      version: 2

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install --ansi
            - source ${BLT_DIR}/scripts/pipelines/setup_env
            # Setup php dependency checker.
            - wget https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.3/local-php-security-checker_2.0.3_linux_amd64
            - mv local-php-security-checker_2.0.3_linux_amd64 local-php-security-checker
            - chmod +x local-php-security-checker
      - validate:
          type: script
          script:
            - source ${BLT_DIR}/scripts/pipelines/validate
      - setup-app:
          type: script
          script:
            - blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --ansi --verbose
      - tests:
          type: script
          script:
            - ./local-php-security-checker
            - source ${BLT_DIR}/scripts/pipelines/tests
      - build-artifact:
          type: script
          script:
            - rm local-php-security-checker
            - source ${BLT_DIR}/scripts/pipelines/build_artifact
