<?php

/**
 * @file
 * Hooks related to the webtools api.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Saves referer to the page containing the form to the form state.
 *
 * The labyrinthine process here is due to form_state storage not persisting if
 * set in initial form load.  And original referer not being available when
 * called again on submission.
 *
 * Implements hook_entity_prepare_form().
 */
function arvestbank_webtools_api_entity_prepare_form(EntityInterface $entity, $operation, FormStateInterface $form_state) {

  // If we have the referrers cookie.
  if (isset($_COOKIE['_arvestbank_webtools__referrers'])) {
    $refererInfo = unserialize($_COOKIE['_arvestbank_webtools__referrers']);
  }
  // If we don't have the referrers cookie.
  else {
    $refererInfo = [];
  }

  // If this is an initial webform load.
  if (
    $entity->getEntityTypeId() == 'webform_submission'
    && !count($form_state->getUserInput())
  ) {

    // If we have a referrer.
    if (isset($_SERVER['HTTP_REFERER'])) {
      $refererInfo[$entity->bundle()] = $_SERVER['HTTP_REFERER'];
    }
    else {
      $refererInfo[$entity->bundle()] = '';
    }

    // Save cookie.
    setcookie('_arvestbank_webtools__referrers', serialize($refererInfo));

  }

  // If this is a webform being submitted and we have the original referrer.
  elseif (
    $entity->getEntityTypeId() == 'webform_submission'
    && count($form_state->getUserInput())
    && isset($refererInfo[$entity->bundle()])
  ) {

    // Store referrer in form state.
    $form_state->set('_arvestbank_webtools__referrer', $refererInfo[$entity->bundle()]);
    // Remove referrer from referrer info.
    unset($refererInfo[$entity->bundle()]);
    // Save cookie.
    setcookie('_arvestbank_webtools__referrers', serialize($refererInfo));

  }

}
