<?php

/**
 * @file
 * Contains arvestbank_calculators.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arvestbank_calculators_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the arvestbank_calculators module.
    case 'help.page.arvestbank_calculators':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Support for embedded calculators from TimeValueCalculators.com.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function arvestbank_calculators_theme() {
  return [
    'arvestbank_calculators_iframe_wrapper' => [
      'render element' => 'children',
      'variables' => ['calc_id' => NULL],
    ],
    'arvestbank_calculators_embed' => [
      'render element' => 'children',
      'variables' => ['calc_id' => NULL],
    ],
  ];
}

//Implements hook_theme_suggestions_HOOK_alter().
function arvestbank_calculators_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'page--cohesion--master-template--arvestbank-theme-calculators-iframe';
  //dump($suggestions);  dump($variables);die();
//  if ($node = \Drupal::routeMatch()->getParameter('node')) {
//    $content_type = $node->bundle();
//    $suggestions[] = 'page__'.$content_type;
//  }
}

/**
 * Implements hook_module_implements_alter().
 */
function arvestbank_calculators_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook_theme_suggestions_page_alter() implementation to the end of the list.
    case 'theme_suggestions_page_alter':
      $group = $implementations['arvestbank_calculators'];
      unset($implementations['arvestbank_calculators']);
      $implementations['arvestbank_calculators'] = $group;
      break;
  }
}

///**
// * Implements hook_preprocess_page().
// *
// * @param $variables
// */
//function arvestbank_calculators_preprocess_block(&$variables) {
//
//  // Get route name from path.
//  $route_name = \Drupal::routeMatch()->getRouteName();
//
//  // Hide elements on the calculators iframe page.
//  if ($route_name == 'arvestbank_calculators.iframe') {
//    $plugin_id = $variables['plugin_id'] ?? null;
//    // Hide site branding.
//    if ($plugin_id == 'system_branding_block') {
//      $variables['content']['site_logo']['#access'] = false;
//      $variables['content']['site_name']['#access'] = false;
//      $variables['content']['site_slogan']['#access'] = false;
//    }
//  }
//
//}
