_core:
  default_config_hash: yHBuI_J_kdrugm0JRNsxHODZ0qQyPzejI6r1ZPacK5Q
shield_enable: true
credential_provider: shield
credentials:
  shield:
    user: arv3st
    pass: arv3st
allow_cli: true
print: Hello!
whitelist: ''
