# The options in this file override the defaults provided by DrupalVM. For a
# comprehensive list of possible options, see DrupalVM's default.config.yml.
# @see https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml

# Update the hostname to the local development environment hostname.
vagrant_hostname: local.arvestbank.com
vagrant_machine_name: arvestbank

# Set the IP address so it doesn't conflict with other Drupal VM instances.
vagrant_ip: 192.168.53.235

# Use Ubuntu 16.04 LTS to match Acquia Cloud environments.
vagrant_box: geerlingguy/drupal-vm
workspace: /root

# Set drupal_site_name to the project's human-readable name.
drupal_site_name: "Arvest Bank"

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `.`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/arvestbank
    type: nfs

drupal_build_composer_project: false
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/arvestbank"
drupal_core_path: "/var/www/arvestbank/docroot"
ssh_home: /var/www/arvestbank

# Multisite installations should configure additional domains here.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"

#  - servername: "local.second-drupal-site.com"
#    documentroot: "{{ drupal_core_path }}"
#    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

# Multisite installations should configure additional databases here.
# It's recommended to prefix database names with 'drupal'. Otherwise,
# you'll need to add additional users in the 'mysql_users' section.
mysql_databases:
  - name: drupal
    encoding: utf8
    collation: utf8_general_ci
#  - name: drupal_two
#    encoding: utf8
#    collation: utf8_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal%.*:ALL"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g., using drush sql-sync).
drupal_install_site: false

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: false

extra_packages: [patchutils, sqlite, libapache2-mod-php7.4]
installed_extras: [adminer, drush, memcached, nodejs, xdebug]

# PHP 7.4.
php_version: "7.4"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - 'php{{ php_version }}-zip'
  - imagemagick

# XDebug configuration.
php_xdebug_version: 2.9.8
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 0
php_xdebug_cli_disable: yes
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"

post_provision_scripts:
  - "../../../acquia/blt-drupal-vm/scripts/drupal-vm/post-provision.php"

apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/vagrant/example.crt"
    certificate_key_file: "/vagrant/example.key"
    extra_parameters: |
      ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

max_allowed_packet: 256M

# composer settings
composer_keep_updated: true # Always update the composer on provision
composer_version_branch: '--2' # Restrict the update to version 2
