ignored_config_entities:
  - '  - ''cohesion_*'''
  - '  - ''webform.webform.*'''
  - '  - acquia_connector.settings'
  - '  - shield.settings'
  - '  - arvestbank_theme.settings'
  - '  - system.theme.global'
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
