module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  cohesion: 0
  cohesion_base_styles: 0
  cohesion_breakpoint_indicator: 0
  cohesion_custom_styles: 0
  cohesion_elements: 0
  cohesion_style_guide: 0
  cohesion_style_helpers: 0
  cohesion_sync: 0
  cohesion_templates: 0
  cohesion_website_settings: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  example_element: 0
  external_link_popup: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gtm: 0
  honeypot: 0
  iframe: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  jsonapi: 0
  link: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  rest: 0
  scheduler: 0
  search: 0
  search404: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simple_instagram_feed: 0
  simplesamlphp_auth: 0
  system: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workflows: 0
  workspaces: 0
  youtube: 0
  pathauto: 1
  externalauth: 10
  views: 10
  minimal: 1000
theme:
  stable: 0
  cohesion_theme: 0
  claro: 0
  arvestbank_theme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
