<?php

/**
 * @file
 * Provides functionality for Arvest Bank menus.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds afterbuild function for canonical menu link functionality.
 *
 * @inheritdoc
 */
function arvestbank_menus_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  // Add an afterbuild for the menu link altering functionality.
  $form['#after_build'][] = '_arvestbank_menus_node_form_canonical_menu_link_alters';

  // Add a submit function to make the menu link canonical on save.
  $form['actions']['submit']['#submit'][] = '_arvestbank_menus_node_form_submit';

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Removes icon attribute from non-social-media menu link edit forms
 * and renames form the social media menu.
 *
 * @inheritdoc
 */
function arvestbank_menus_form_menu_link_content_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Get menu name.
  $menu_name = $form_state->getformObject()->getEntity()->getMenuName();

  // If this is the social media menu.
  if ($menu_name == 'social-media-menu') {
    // After build function to rename second attribute fieldgroup label.
    $form['#after_build'][] = '_arvestbank_menus_rename_second_attribute_fieldgroup';
  }
  // For all other menus.
  else {
    // After build function to remove second attribute fieldgroup label.
    $form['#after_build'][] = '_arvestbank_menus_remove_second_attribute_fieldgroup';
  }

}

/**
 * Make the submitted menu link (if any) canonical.
 *
 * @param array $form
 *   The form to alter.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The formstate.
 */
function _arvestbank_menus_node_form_submit(array $form, FormStateInterface $form_state) {

  // If we have form state values for a menu link.
  if (!$form_state->isValueEmpty('menu')) {
    // Get values for the menu link.
    $values = $form_state->getValue('menu');
    // If we have a menu link id.
    if ($values['entity_id']) {
      // Get the node this form is for.
      $node = $form_state->getFormObject()->getEntity();
      // Get canonical menu link helper service.
      $canonicalMenuLinkHelper = \Drupal::service('arvestbank_menus.canonical_menu_link_helper');
      // Set this menu link as the canonical one.
      $canonicalMenuLinkHelper->makeLinkCanonical($values['entity_id']);
    }
  }

}

/**
 * Afterbuild function for canonical menu link functionality.
 *
 * @param array $form
 *   The form to alter.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The formstate.
 *
 * @return array
 *   Returns the altered form.
 */
function _arvestbank_menus_node_form_canonical_menu_link_alters(array $form, FormStateInterface &$form_state) {

  // Get the node this form is for.
  $node = $form_state->getFormObject()->getEntity();

  // Get menu link values from the form state.
  $defaultMenuValues = $form_state->getValue('menu');

  // Get canonical menu link helper service.
  $canonicalMenuLinkHelper = \Drupal::service('arvestbank_menus.canonical_menu_link_helper');
  // Get canonical menu link for this node.
  $canonicalMenuLinkId = $canonicalMenuLinkHelper->getCanonicalMenuLinkIds($node->id(), TRUE);

  // If there is a canonical menu link for this node.
  // And the default menu item shown isn't the canonical menu link.
  if (
    $canonicalMenuLinkId
    && $defaultMenuValues['entity_id'] != $canonicalMenuLinkId
  ) {

    // Get field defaults for canonical menu link.
    $canonicalMenuLinkDefaults = $canonicalMenuLinkHelper->getLinkFieldDefaults($canonicalMenuLinkId);

    // Loop over the default menu values in the form state.
    foreach ($defaultMenuValues as $defaultMenuValueKey => $defaultMenuValueValue) {

      // If the canonical link also has a value for this.
      if (isset($canonicalMenuLinkDefaults[$defaultMenuValueKey])) {
        // Replace the value in the form state with the canonical one.
        $defaultMenuValues[$defaultMenuValueKey] = $canonicalMenuLinkDefaults[$defaultMenuValueKey];
      }

      // If there is a form field with a value we can set for this.
      if (isset($form['menu']['link'][$defaultMenuValueKey]['#value'])) {
        // Set the value to the canonical one.
        $form['menu']['link'][$defaultMenuValueKey]['#value'] = $canonicalMenuLinkDefaults[$defaultMenuValueKey];
      }

      // If there is a form field with a default value we can set for this.
      if (isset($form['menu']['link'][$defaultMenuValueKey]['#default_value'])) {
        // Set the value to the canonical one.
        $form['menu']['link'][$defaultMenuValueKey]['#default_value'] = $canonicalMenuLinkDefaults[$defaultMenuValueKey];
      }

    }

    // Set the menu link values.
    $form_state->setValue('menu', $defaultMenuValues);

  }

  return $form;
}

/**
 * Afterbuild function to rename second attribute fieldgroup.
 *
 * @param array $form
 *   The form to alter.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The formstate.
 *
 * @return array
 *   Returns the altered form.
 */
function _arvestbank_menus_rename_second_attribute_fieldgroup(array $form, FormStateInterface &$form_state) {
  // Change the fieldgroup title.
  $form['options']['attributes']['#title'] = 'Select Link Icon';
  return $form;
}

/**
 * Afterbuild function to remove second attribute fieldgroup.
 *
 * @param array $form
 *   The form to alter.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The formstate.
 *
 * @return array
 *   Returns the altered form.
 */
function _arvestbank_menus_remove_second_attribute_fieldgroup(array $form, FormStateInterface &$form_state) {
  // Remove fieldgroup from the form.
  unset($form['options']);
  return $form;
}

/**
 * Set canonical field false for other menulinks to same node this one goes to.
 *
 * @param Drupal\Core\Entity\EntityInterface $entity
 *   The entity being saved.
 */
function arvestbank_menus_entity_presave(EntityInterface $entity) {

  if (

    // If this is a menu link.
    $entity->getEntityType()->id() == 'menu_link_content'

    // If this menu link is to a node.
    && $entity->getUrlObject()
    && isset($entity->getUrlObject()->getRouteParameters()['node'])

    // If this menu link is set as canonical.
    && $entity->hasField('field_canonical_menu_item')
    && isset($entity->get('field_canonical_menu_item')->getValue()[0]['value'])
    && $entity->get('field_canonical_menu_item')->getValue()[0]['value']

    // If this menu link was not set to canonical before.
    // This prevents recursion when links are made non-canonical and saved.
    && $entity->original->hasField('field_canonical_menu_item')
    && (
      !isset($entity->original->get('field_canonical_menu_item')->getValue()[0]['value'])
      || !$entity->original->get('field_canonical_menu_item')->getValue()[0]['value']
    )

  ) {

    // Get canonical menu link helper service.
    $canonicalMenuLinkHelper = \Drupal::service('arvestbank_menus.canonical_menu_link_helper');
    // Get referenced node.
    $referencedNodeId = $entity->getUrlObject()->getRouteParameters()['node'];
    // Get set other menu links to the referenced node as non-canonical.
    $canonicalMenuLinkHelper->setOtherNodeLinksToNonCanonical($referencedNodeId, $entity->id());

  }

}
