<?php

/**
 * @file
 * Contains arvestbank_ads.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function arvestbank_ads_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the arvestbank_ads module.
    case 'help.page.arvestbank_ads':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom ads management.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function arvestbank_ads_theme(): array {
  return [
    'ad_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function arvestbank_ads_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  // Add descriptions of paths for sidebar ad placement fields.
  if ($form_id == 'node_ad_campaign_edit_form') {

    // Get the map of paths to fields from the service.
    $fieldmap = \Drupal::service('ad_services')->getSidebarFieldMap();

    // Loop through this array and set the description to the path(s) (key).
    foreach ($fieldmap as $path => $fieldname) {
      if (!empty($form[$fieldname]['widget'])) {
        $description = $path . '<br />';
        $form[$fieldname]['widget']['#description'] .= $description;
      }
    }

  }

}
