<?php

/**
 * @file
 * Hooks relating to revisions on the Arvest Bank site.
 */

use Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function arvestbank_revisions_form_revision_overview_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  foreach ($form['node_revisions_table'] as $renderArrayChildKey => $renderArrayChildValue) {
    if (
      is_numeric($renderArrayChildKey)
      && isset($renderArrayChildValue['operations']['#links']['delete'])
    ) {
      unset($form['node_revisions_table'][$renderArrayChildKey]['operations']['#links']['delete']);
    }
  }

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function arvestbank_revisions_form_node_form_alter(&$form, &$form_state, $form_id) {

  // Define the content types to force revisions for.
  // Workflow does this for bundles under it's control.
  $contentTypesToForceRevisionsFor = [
    'cta_phone_number',
    'associate',
  ];

  // Get the node this form is for.
  $node = $form_state->getFormObject()->getEntity();

  if (in_array($node->bundle(), $contentTypesToForceRevisionsFor)) {
    // Require revisions.
    // Taken from NodeModerationHandler->enforceRevisionsEntityFormAlter().
    $form['revision']['#disabled'] = TRUE;
    $form['revision']['#default_value'] = TRUE;
    $form['revision']['#description'] = 'Revisions are required.';
  }


}

/**
 * Implements hook_tokens_alter().
 */
function arvestbank_revisions_tokens_alter(array &$replacements, array $context, BubbleableMetadata $bubbleable_metadata) {

  // If this is the current page title token on a revision page.
  if (
    isset($context['tokens']['title'])
    && $context['tokens']['title'] == '[current-page:title]'
    && \Drupal::request()->get('_raw_variables')
    && \Drupal::request()->get('_raw_variables')->get('node_revision')
  ) {
    // Strip tags from the title.
    $replacements['[current-page:title]'] = strip_tags($replacements['[current-page:title]']);
  }

}
